--------------------------------------------------------
--  File created - Friday-December-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "CATEGORIES" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES_RELATIONS
--------------------------------------------------------

  CREATE TABLE "CATEGORIES_RELATIONS" 
   (	"ID" NUMBER(*,0), 
	"CATEGORIES_ID" NUMBER(*,0), 
	"CATEGORIES_ID1" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHATS
--------------------------------------------------------

  CREATE TABLE "CHATS" 
   (	"ID" NUMBER(*,0), 
	"USERS_ID" NUMBER(*,0), 
	"USERS_ID1" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "COMMENTS" 
   (	"ID" NUMBER(*,0), 
	"comment" VARCHAR2(300 BYTE), 
	"USERS_ID" NUMBER(*,0), 
	"POSTS_ID" NUMBER(*,0), 
	"COMMENTS_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDUCATION
--------------------------------------------------------

  CREATE TABLE "EDUCATION" 
   (	"ID" NUMBER(*,0), 
	"INSTITUTE" VARCHAR2(100 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE), 
	"GRADE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOWING
--------------------------------------------------------

  CREATE TABLE "FOLLOWING" 
   (	"ID" NUMBER(19,0), 
	"FROM" NUMBER(10,0), 
	"TO" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "JOBS" 
   (	"ID" NUMBER(*,0), 
	"USERS_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORY" NUMBER, 
	"LOCATION" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIKES
--------------------------------------------------------

  CREATE TABLE "LIKES" 
   (	"ID" NUMBER(*,0), 
	"USERS_ID" NUMBER(*,0), 
	"POSTS_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "LOCATIONS" 
   (	"ID" NUMBER(*,0), 
	"LOCATION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "MESSAGES" 
   (	"ID" NUMBER(*,0), 
	"CHATS_ID" NUMBER(*,0), 
	"MENSSAGE" VARCHAR2(300 BYTE), 
	"USERS_ID" NUMBER(*,0), 
	"DATEMSG" DATE, 
	"SEEN" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MY_EDUCATION
--------------------------------------------------------

  CREATE TABLE "MY_EDUCATION" 
   (	"USERS_ID" NUMBER(*,0), 
	"EDUCATION_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"FINISH_DATE" DATE, 
	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MY_EXPERIENCE
--------------------------------------------------------

  CREATE TABLE "MY_EXPERIENCE" 
   (	"USERS_ID" NUMBER(*,0), 
	"WORK_EXPERIENCE_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"FINISH_DATE" DATE, 
	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MY_SKILLS
--------------------------------------------------------

  CREATE TABLE "MY_SKILLS" 
   (	"USERS_ID" NUMBER(*,0), 
	"SKILLS_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "NOTIFICATIONS" 
   (	"ID" NUMBER(*,0), 
	"CONTENT" VARCHAR2(100 BYTE), 
	"POSTS_ID" NUMBER(*,0), 
	"USERS_ID" NUMBER(*,0), 
	"USERS_ID1" NUMBER(*,0), 
	"TYPENOTI" VARCHAR2(10 BYTE), 
	"PENNDING" CHAR(1 BYTE) DEFAULT 1
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATIONS_REPORT
--------------------------------------------------------

  CREATE TABLE "NOTIFICATIONS_REPORT" 
   (	"NOTIFICATIONS_ID" NUMBER(*,0), 
	"ISSEEN" CHAR(1 BYTE), 
	"USERS_ID" NUMBER(*,0), 
	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "POSTS" 
   (	"ID" NUMBER(19,0), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"MEDIA" VARCHAR2(500 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATEPOST" VARCHAR2(20 BYTE), 
	"USERS_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILLS
--------------------------------------------------------

  CREATE TABLE "SKILLS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"PHOTO" VARCHAR2(400 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"INFO" VARCHAR2(300 BYTE), 
	"BANNER" VARCHAR2(200 BYTE), 
	"LOCATIONS_ID" NUMBER, 
	"CATEGORIES_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK_EXPERIENCE
--------------------------------------------------------

  CREATE TABLE "WORK_EXPERIENCE" 
   (	"ID" NUMBER(*,0), 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE), 
	"OCCUPATION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CATEGORIES

--------------------------------------------------------
--  DDL for Index CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATEGORIES_PK" ON "CATEGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHATS_PK" ON "CHATS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMMENTS__IDX" ON "COMMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EDUCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUCATION_PK" ON "EDUCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOLLOWING_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOLLOWING_ID_PK" ON "FOLLOWING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JOBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOBS_PK" ON "JOBS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LIKES__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "LIKES__IDX" ON "LIKES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOCATIONS_PK" ON "LOCATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MESSAGES__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MESSAGES__IDX" ON "MESSAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MY_EDUCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MY_EDUCATION_PK" ON "MY_EDUCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MY_EXPERIENCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MY_EXPERIENCE_PK" ON "MY_EXPERIENCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTIFICATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTIFICATIONS_PK" ON "NOTIFICATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTIFICATIONS_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTIFICATIONS_REPORT_PK" ON "NOTIFICATIONS_REPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POSTS_PK" ON "POSTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKILLS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKILLS_PK" ON "SKILLS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL_UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERS_EMAIL_UNV1" ON "USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORK_EXPERIENCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WORK_EXPERIENCE_PK" ON "WORK_EXPERIENCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CATEGORIES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CATEGORIES_TRG" 
BEFORE INSERT ON CATEGORIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CATEGORIES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CATEGORIES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAT_TGR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CAT_TGR" 
   before insert on "CATEGORIES" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select CATEGORIES_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CAT_TGR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHATS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CHATS_TRG" 
BEFORE INSERT ON CHATS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CHATS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CHATS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "COMMENTS_TRG" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT COMMENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "COMMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CM_TG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CM_TG" 
   before insert on "COMMENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select COMMENTS_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CM_TG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EDUCATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "EDUCATION_TRG" 
BEFORE INSERT ON EDUCATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EDUCATION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EDUCATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOLLOWING_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FOLLOWING_ID_TRG" 
            before insert on FOLLOWING
            for each row
                begin
            if :new.ID is null then
                select following_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "FOLLOWING_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JOBS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "JOBS_TRG" 
   before insert on "JOBS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select JOBS_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "JOBS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LIKES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "LIKES_TRG" 
BEFORE INSERT ON LIKES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIKES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LIKES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "LOCATIONS_TRG" 
BEFORE INSERT ON LOCATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LOCATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOCATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCSEQ
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "LOCSEQ" 
   before insert on "LOCATIONS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select LOCATIONS_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "LOCSEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MESSAGES_TRG1" 
BEFORE INSERT ON MESSAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MESSAGES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MESSAGES_TRG" 
BEFORE INSERT ON MESSAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MESSAGES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGES_TRG2
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MESSAGES_TRG2" 
BEFORE INSERT ON MESSAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MESSAGES_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MESSAGES_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MY_EDUCATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MY_EDUCATION_TRG" 
BEFORE INSERT ON MY_EDUCATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MY_EDUCATION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MY_EDUCATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MYEDU_TGR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MYEDU_TGR" 
   before insert on "MY_EDUCATION" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select MY_EDUCATION_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "MYEDU_TGR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MY_EXPERIENCE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MY_EXPERIENCE_TRG" 
BEFORE INSERT ON MY_EXPERIENCE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MY_EXPERIENCE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MY_EXPERIENCE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MYEXP_TGR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MYEXP_TGR" 
   before insert on "MY_EXPERIENCE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select MY_EXPERIENCE_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "MYEXP_TGR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "NOTIFICATIONS_TRG" 
BEFORE INSERT ON NOTIFICATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "NOTIFICATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICATIONS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "NOTIFICATIONS_TRG1" 
BEFORE INSERT ON NOTIFICATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NOTIFICATIONS_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "NOTIFICATIONS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICATIONS_REPORT_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "NOTIFICATIONS_REPORT_TRG" 
BEFORE INSERT ON NOTIFICATIONS_REPORT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NOTIFICATIONS_REPORT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "NOTIFICATIONS_REPORT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "POSTS_TRG" 
BEFORE INSERT ON POSTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "POSTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSTS_TG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "POSTS_TG" 
   before insert on "POSTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select POSTS_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "POSTS_TG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_TG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "USER_TG" 
   before insert on "USERS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select USERS_ID_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "USER_TG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger WORK_EXPERIENCE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "WORK_EXPERIENCE_TRG" 
BEFORE INSERT ON WORK_EXPERIENCE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT WORK_EXPERIENCE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WORK_EXPERIENCE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "CATEGORIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CATEGORIES" ADD CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES_RELATIONS
--------------------------------------------------------

  ALTER TABLE "CATEGORIES_RELATIONS" MODIFY ("CATEGORIES_ID" NOT NULL ENABLE);
  ALTER TABLE "CATEGORIES_RELATIONS" MODIFY ("CATEGORIES_ID1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHATS
--------------------------------------------------------

  ALTER TABLE "CHATS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CHATS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "CHATS" MODIFY ("USERS_ID1" NOT NULL ENABLE);
  ALTER TABLE "CHATS" ADD CONSTRAINT "CHATS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("POSTS_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX "COMMENTS__IDX"  ENABLE;
  ALTER TABLE "COMMENTS" MODIFY ("comment" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "EDUCATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDUCATION" ADD CONSTRAINT "EDUCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLLOWING
--------------------------------------------------------

  ALTER TABLE "FOLLOWING" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING" MODIFY ("FROM" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING" MODIFY ("TO" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FOLLOWING_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "JOBS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JOBS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "JOBS" ADD CONSTRAINT "JOBS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "LIKES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LIKES" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "LIKES" MODIFY ("POSTS_ID" NOT NULL ENABLE);
  ALTER TABLE "LIKES" ADD CONSTRAINT "LIKES_PK" PRIMARY KEY ("ID")
  USING INDEX "LIKES__IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "LOCATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOCATIONS" ADD CONSTRAINT "LOCATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "MESSAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("CHATS_ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" ADD CONSTRAINT "MESSAGES_PK" PRIMARY KEY ("ID")
  USING INDEX "MESSAGES__IDX"  ENABLE;
  ALTER TABLE "MESSAGES" MODIFY ("MENSSAGE" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("DATEMSG" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("SEEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MY_EDUCATION
--------------------------------------------------------

  ALTER TABLE "MY_EDUCATION" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EDUCATION" MODIFY ("EDUCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EDUCATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EDUCATION" ADD CONSTRAINT "MY_EDUCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MY_EXPERIENCE
--------------------------------------------------------

  ALTER TABLE "MY_EXPERIENCE" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EXPERIENCE" MODIFY ("WORK_EXPERIENCE_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EXPERIENCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MY_EXPERIENCE" ADD CONSTRAINT "MY_EXPERIENCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MY_SKILLS
--------------------------------------------------------

  ALTER TABLE "MY_SKILLS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_SKILLS" MODIFY ("SKILLS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "NOTIFICATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS" MODIFY ("USERS_ID1" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICATIONS_REPORT
--------------------------------------------------------

  ALTER TABLE "NOTIFICATIONS_REPORT" MODIFY ("NOTIFICATIONS_ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS_REPORT" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS_REPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATIONS_REPORT" ADD CONSTRAINT "NOTIFICATIONS_REPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "POSTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "POSTS" MODIFY ("USERS_ID" NOT NULL ENABLE);
  ALTER TABLE "POSTS" ADD CONSTRAINT "POSTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "POSTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "POSTS" MODIFY ("DATEPOST" NOT NULL ENABLE);
  ALTER TABLE "POSTS" MODIFY ("MEDIA" NOT NULL ENABLE);
  ALTER TABLE "POSTS" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKILLS
--------------------------------------------------------

  ALTER TABLE "SKILLS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKILLS" ADD CONSTRAINT "SKILLS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_EMAIL_UNV1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORK_EXPERIENCE
--------------------------------------------------------

  ALTER TABLE "WORK_EXPERIENCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WORK_EXPERIENCE" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "WORK_EXPERIENCE" ADD CONSTRAINT "WORK_EXPERIENCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIES_RELATIONS
--------------------------------------------------------

  ALTER TABLE "CATEGORIES_RELATIONS" ADD CONSTRAINT "CATEGORIES_FK" FOREIGN KEY ("CATEGORIES_ID")
	  REFERENCES "CATEGORIES" ("ID") ENABLE;
  ALTER TABLE "CATEGORIES_RELATIONS" ADD CONSTRAINT "CATEGORIES_FKV2" FOREIGN KEY ("CATEGORIES_ID1")
	  REFERENCES "CATEGORIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHATS
--------------------------------------------------------

  ALTER TABLE "CHATS" ADD CONSTRAINT "CHATS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
  ALTER TABLE "CHATS" ADD CONSTRAINT "CHATS_USERS_FKV2" FOREIGN KEY ("USERS_ID1")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_COMMENTS_FK" FOREIGN KEY ("COMMENTS_ID")
	  REFERENCES "COMMENTS" ("ID") ENABLE;
  ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_POSTS_FK" FOREIGN KEY ("POSTS_ID")
	  REFERENCES "POSTS" ("ID") ENABLE;
  ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "JOBS" ADD CONSTRAINT "JOBS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "LIKES" ADD CONSTRAINT "LIKES_POSTS_FK" FOREIGN KEY ("POSTS_ID")
	  REFERENCES "POSTS" ("ID") ENABLE;
  ALTER TABLE "LIKES" ADD CONSTRAINT "LIKES_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MY_EDUCATION
--------------------------------------------------------

  ALTER TABLE "MY_EDUCATION" ADD CONSTRAINT "MY_EDUCATION_EDUCATION_FK" FOREIGN KEY ("EDUCATION_ID")
	  REFERENCES "EDUCATION" ("ID") ENABLE;
  ALTER TABLE "MY_EDUCATION" ADD CONSTRAINT "MY_EDUCATION_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MY_EXPERIENCE
--------------------------------------------------------

  ALTER TABLE "MY_EXPERIENCE" ADD CONSTRAINT "MY_EXPERIENCE_FK" FOREIGN KEY ("WORK_EXPERIENCE_ID")
	  REFERENCES "WORK_EXPERIENCE" ("ID") ENABLE;
  ALTER TABLE "MY_EXPERIENCE" ADD CONSTRAINT "MY_EXPERIENCE_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MY_SKILLS
--------------------------------------------------------

  ALTER TABLE "MY_SKILLS" ADD CONSTRAINT "MY_SKILLS_SKILLS_FK" FOREIGN KEY ("SKILLS_ID")
	  REFERENCES "SKILLS" ("ID") ENABLE;
  ALTER TABLE "MY_SKILLS" ADD CONSTRAINT "MY_SKILLS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_POSTS_FK" FOREIGN KEY ("POSTS_ID")
	  REFERENCES "POSTS" ("ID") ENABLE;
  ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
  ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_USERS_FKV2" FOREIGN KEY ("USERS_ID1")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS_REPORT
--------------------------------------------------------

  ALTER TABLE "NOTIFICATIONS_REPORT" ADD CONSTRAINT "NOTIFICATIONS_REPORT_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_CATEGORIES_FK" FOREIGN KEY ("CATEGORIES_ID")
	  REFERENCES "CATEGORIES" ("ID") ENABLE;
  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_LOCATIONS_FK" FOREIGN KEY ("LOCATIONS_ID")
	  REFERENCES "LOCATIONS" ("ID") ENABLE;
--------------------------------------------------------
--  File created - Friday-December-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "APPLICATIONS" 
   (	"JOBS_ID" NUMBER(*,0), 
	"USERS_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into APPLICATIONS

--------------------------------------------------------
--  Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "APPLICATIONS" MODIFY ("JOBS_ID" NOT NULL ENABLE);
  ALTER TABLE "APPLICATIONS" MODIFY ("USERS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_JOBS_FK" FOREIGN KEY ("JOBS_ID")
	  REFERENCES "JOBS" ("ID") ENABLE;
  ALTER TABLE "APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_USERS_FK" FOREIGN KEY ("USERS_ID")
	  REFERENCES "USERS" ("ID") ENABLE;

INSERT INTO "USER1"."SKILLS" (ID, NAME) VALUES ('1', 'LARAVEL')
INSERT INTO "USER1"."SKILLS" (ID, NAME) VALUES ('2', 'JAVA')
INSERT INTO "USER1"."SKILLS" (ID, NAME) VALUES ('3', 'NODEJS')
INSERT INTO "USER1"."CATEGORIES" (ID, NOMBRE) VALUES ('1', 'USUARIO')
